"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ORDER_TRANSITIONS = void 0;
exports.ORDER_TRANSITIONS = {
    PENDING_PAYMENT: ['PAYMENT_DETECTED', 'EXPIRED'],
    PAYMENT_DETECTED: ['PAYMENT_CONFIRMED', 'EXPIRED', 'EXTRA_PAYMENT'],
    PAYMENT_CONFIRMED: ['DISPATCH_ENQUEUED', 'EXTRA_PAYMENT'],
    DISPATCH_ENQUEUED: ['DISPATCH_SENT', 'FULFILL_FAILED_MANUAL'],
    DISPATCH_SENT: ['FULFILLED', 'FULFILL_FAILED_MANUAL'],
    FULFILLED: [],
    FULFILL_FAILED_MANUAL: [],
    EXPIRED: ['EXTRA_PAYMENT'],
    EXTRA_PAYMENT: [],
};
